"""empty message

Revision ID: cb53ebdedf77
Revises: 99e76097b634
Create Date: 2021-11-05 15:24:21.360979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb53ebdedf77'
down_revision = '99e76097b634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'release_date')
    # ### end Alembic commands ###
